language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - nosetests -v --with-coverage
  - pyflakes highlight.py time_utils.py utils.py
  - pylint -d all -e W0611,W0612,W0613,W0614 --reports=n --msg-template='{msg_id} {path}:{line} {msg} ({symbol})' highlight.py time_utils.py utils.py
after_success:
  coveralls
